version: "2"
services:
    movie-server:
        image: movie-server
        build: ./
        environment: 
            API_HOST: ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT}
        expose: 
            - ${APP_SERVER_PORT}
        ports:
            - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
        depends_on:
            - mongo
        command: npm start
    mongo:
        image: mongo
        ports:
            - "27017:27017"